[package]
name = "jclass"
version = "0.1.0"
edition = "2024"

[features]
default = []
javap_print = []
jasm_assemble = []

[dependencies]
num_enum = "0.7.4"
itertools = "0.14.0"

either = "1.15.0" # TODO: add only under javap_print feature

common = { path = "../common" }

[dev-dependencies]


